version: "3"

services:
  app:
      image: quay.io/keycloak/keycloak:20.0.2
      container_name: keycloak
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        PROXY_ADDRESS_FORWARDING: "true"
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin   
      ports:
        - 8080:8080
      command:
        - start-dev  
      depends_on:
        - postgres      

  postgres:
    image: postgres:12.2
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
